print("ilia: hi everybody")
print("oshri: hi ilia")
print("Yoni: This is confusing.....")
print("Elad: wake UP!")
print("Hi im Dugibeat")
print("no conflicts please")
print("ilia: why none commits anything")
